# Generated by Django 5.2.14 on 2026-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_add_salarys'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorregis',
            name='Role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
