# Generated by Django 6.0.5 on 2026-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_authorregis_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_room',
            name='Room_Status',
            field=models.CharField(choices=[('Trống', 'Trống'), ('Đã Đặt', 'Đã Đặt'), ('Bảo Trì', 'Bảo Trì')], default='Trống', max_length=50),
        ),
        migrations.AlterModelTable(
            name='add_employee',
            table=None,
        ),
        migrations.AlterModelTable(
            name='authorregis',
            table=None,
        ),
        migrations.AlterModelTable(
            name='offline_booking',
            table=None,
        ),
        migrations.AlterModelTable(
            name='online_booking',
            table=None,
        ),
    ]
