# Generated by Django 5.2.14 on 2026-06-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_add_room_room_status_alter_add_employee_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_room',
            name='Room_Status',
        ),
        migrations.AddField(
            model_name='online_booking',
            name='Room_Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='add_employee',
            table='Add_Employees',
        ),
        migrations.AlterModelTable(
            name='authorregis',
            table='Authority_reg',
        ),
        migrations.AlterModelTable(
            name='offline_booking',
            table='Offline_Booking_Customer',
        ),
        migrations.AlterModelTable(
            name='online_booking',
            table='HotelApp_online_booking',
        ),
    ]
